# Generated by Django 4.2.5 on 2023-09-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="engine",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item", name="winglet", field=models.BooleanField(default=False),
        ),
    ]
