# Generated by Django 3.2.6 on 2023-09-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_engine_item_winglet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='engine',
            field=models.CharField(choices=[('Jet', 'Jet'), ('Propeller', 'Propeller')], max_length=255, null=True),
        ),
    ]
